import "./styles/globals.css";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Rubik, Roboto } from "next/font/google";

// Initialize Rubik font
const rubik = Rubik({
  subsets: ["latin", "arabic"],
  variable: "--font-rubik",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

// Initialize Roboto font
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="auto">
      <body
        className={`${rubik.variable} ${roboto.variable} min-h-svh bg-neutral-100 font-rubik font-normal antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
